### ISSUE TITLE
Don't use contact hash

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.newsletter#11]
Instead of CiviCRM's contact hash, you should be using CiviCRM's checksum, see e.g. [HERE](https://github.com/systopia/de.systopia.selfservice/blob/0.2/CRM/Selfservice/HashLinks.php#L82).

Since CiviCRM's contact hash doesn't change or expire, it's unwise to send it out as-is.

**Comment by jensschuppe** [comment]
I'd really like to implement this before a stable `1.0`.
