### ISSUE TITLE
Prefix field shows deactivated options

### ISSUE THREAD

**Issue by AHowiller** [systopia/de.systopia.newsletter#14]
When the prefix contact field is used the submission form should only present currently activated options. 

Version info:
this extension: 1.0-alpha4
remote Drupal module: 1.0-beta4

**Comment by jensschuppe** [comment]
The code to be adjusted ist this:
https://github.com/systopia/de.systopia.newsletter/blob/120c3387c453f2d9bd9fcca4e2d27778b1ff5897/CRM/Newsletter/Profile.php#L220-L223

Would you be able to provide a PR, @AHowiller?
