### ISSUE TITLE
Default Opt-In URL, Preferences URL, Request link URL

### ISSUE THREAD

**Issue by jojowork** [systopia/de.systopia.newsletter#26]
The Fields in a Advanced Newsletter Management Profile should have the following default values:

-  Opt-in URL: `SITE-URL`/civicrm_newsletter/optin/[PROFILE]/[CONTACT_HASH]`
-  Preferences URL: `SITE-URL`/civicrm_newsletter/preferences/[PROFILE]/[CONTACT_HASH]
-  Request link URL: `SITE-URL`/civicrm_newsletter/request_link/[PROFILE]/[CONTACT_HASH]

Because these are the default values if you use this extension together with the Drupal Module [civicrm_newsletter](https://github.com/systopia/civicrm_newsletter) which is the most used frontend-implementation for this extension. This would make the configuration significantly easier.

**Comment by jensschuppe** [comment]
Would you be fine with those URLs be mentioned as an example in the fields' descriptions only?

I'd rather not provide default values that will not always work, as there will be no note to the user when they miss reviewing those default values. With explicitly no initial values in those required fields, there will be error messages when saving the form, which serve as a good reminder for really understanding what needs to be in there.

**Comment by jojowork** [comment]
This would already be an improvement.
I guess the right place to change this is here: https://github.com/systopia/de.systopia.newsletter/blob/7ff5a0ff1813eceb452a587e2a12162c976a4284/templates/CRM/Newsletter/Form/Profile.tpl#L56C1-L56C221
I could provide an PR for this.

**Comment by jojowork** [comment]
@jensschuppe can you have a look at the PR #27
