### ISSUE TITLE
Token hook implementation triggers PHP warning: Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.newsletter#5]
The implementation of the token hook here

https://github.com/systopia/de.systopia.newsletter/blob/ee144ce76789b224f7afa126bde101e8e3fcd256/newsletter.php#L205

triggers a PHP warning:
```
Invalid argument supplied for foreach() newsletter.php:205 [warning]
```

See also: https://github.com/systopia/de.systopia.sqltasks/issues/78

**Comment by jensschuppe** [comment]
Thanks @bjendres!
