### ISSUE TITLE
Create an unsubscribe all mechanism

### ISSUE THREAD

**Issue by pbatroff** [systopia/de.systopia.newsletter#8]
There should be an option to create an unsubscribeAll button in the setup back-end, as well as a separate confirmation Email Edit and an API to be called when unsubscribing a contact from all groups. 

(see dev_12861)

**Comment by pbatroff** [comment]
There should be another option in the civicrm configuration back end to decide whether

1. an unsubscribe should work for _all_ groups from all profiles
2. an unsubscribe should only work for groups in this specific profile

**Comment by jensschuppe** [comment]
Will be released with version 0.12
